/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import "NethackApp.h"

void main(int argc, char *argv[]) {

    [NethackApp new];
    if ([NXApp loadNibSection:"Nethack.nib" owner:NXApp withNames:NO])
	    [NXApp run];
	    
    [NXApp free];
    exit(0);
}
